### ISSUE TITLE
MHS 400 Mitosis - Slide info

### ISSUE THREAD

**Issue by giuseb** [giuseb/histologyguide#23]
The info for [this slide](https://histologyguide.org/slideview/MHS-400-mitosis/01-slide-1.html) seems wrong.

<img width="695" alt="image" src="https://github.com/giuseb/histologyguide/assets/10086/bd04ecca-b58d-4173-9ae2-02233401ff98">

**Comment by Brelje** [comment]
* Most of the photos do not have scale bars.  This pixel size was most likely not updated when created in 2012.  The new pixel size was estimated from structures seen in the micrograph.  For this image, the thickness of the intermediate filament (10 nm), desmosome diameter (200 to 500 nm), width of extracellular region (34 nm), and width of inner dense plaque (15-20 nm) were used.  The pixel size changed 10-fold from 0.04095 to 0.4520 nm/pixel.  The intermediate filaments are now ~10 nm in diameter.
* The slide information has been updated.
* The colored image was also replaced with a better version using techniques learned since 2012.

**Comment by Brelje** [comment]
* Looks like slide information was only partially updated when created.
* Fixed the thumbnail 
* The image was also replaced with one with better color and brightness.
